### ISSUE TITLE
llama3.1-8b-it 模型加载报错

### ISSUE THREAD

**Issue by DragonFive** [zhihu/ZhiLight#19]
同样的模型 vllm/sglang/tgi3 都是ok的

```
17:06:53.763 Traceback (most recent call last):
17:06:53.763   File "/usr/local/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
17:06:53.764     return _run_code(code, main_globals, None,
17:06:53.764   File "/usr/local/conda/lib/python3.9/runpy.py", line 87, in _run_code
17:06:53.764     exec(code, run_globals)
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/server/openai/entrypoints/api_server.py", line 168, in <module>
17:06:53.764     engine = AsyncLLMEngine.from_engine_args(engine_args)
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/server/openai/engine/async_llm_engine.py", line 161, in from_engine_args
17:06:53.764     engine = cls(engine_config,
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/server/openai/engine/async_llm_engine.py", line 143, in __init__
17:06:53.764     self.engine = self._engine_class(engine_config = engine_config, log_stats = log_stats)
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/server/openai/engine/llm_engine.py", line 39, in __init__
17:06:53.764     self._instance = LLaMA(
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/llama.py", line 133, in __init__
17:06:53.764     self._init_tokenizer(vocab_path, tokenizer)
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/zhilight/llama.py", line 158, in _init_tokenizer
17:06:53.764     self._tokenizer.eos_token_id = self._config.get("eos_token_id", None) or 2
17:06:53.764   File "/usr/local/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1077, in __setattr__
17:06:53.764     raise ValueError(f"Cannot set a non-string value as the {key}")
17:06:53.764 ValueError: Cannot set a non-string value as the eos_token

```

**Comment by DragonFive** [comment]
#20  this pr fix it
