### ISSUE TITLE
源码安装后，运行报错

### ISSUE THREAD

**Issue by ChuanhongLi** [zhihu/ZhiLight#6]
(zhihu_infer) root@localhost:~# pip3 list | grep zhilight
zhilight                          0.4.8

执行服务部署时，报错：
python -m zhilight.server.openai.entrypoints.api_server --model-path /workspace/sdb/models/QWen2.5/Qwen2.5-7B-Instruct-GPTQ-Int4
Traceback (most recent call last):
  File "/miniconda/envs/zhihu_infer/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/miniconda/envs/zhihu_infer/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/miniconda/envs/zhihu_infer/lib/python3.10/site-packages/zhilight-0.4.8-py3.10-linux-x86_64.egg/zhilight/__init__.py", line 2, in <module>
    from .llama import LLaMA
  File "/miniconda/envs/zhihu_infer/lib/python3.10/site-packages/zhilight-0.4.8-py3.10-linux-x86_64.egg/zhilight/llama.py", line 11, in <module>
    from . import C
ImportError: /miniconda/envs/zhihu_infer/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /miniconda/envs/zhihu_infer/lib/python3.10/site-packages/zhilight-0.4.8-py3.10-linux-x86_64.egg/zhilight/C.cpython-310-x86_64-linux-gnu.so)
(zhihu_infer) root@localhost:~#

**Comment by unix1986** [comment]
像是哪里gcc版本不对应，但是信息量太少，很难给予有效帮助，你用我们的Docker镜像试试呢

**Comment by ZonePG** [comment]
conda install -c conda-forge libstdcxx-ng

**Comment by spetrel** [comment]
Can you try uninstall libstdcxx-ng ?
